on: [push]
name: Deploy Bicep template
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Getting Started
        run: |
          echo Hello from GithubActions
        