name: Deploy Rules

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master


# env:
#   CONFIG_FILE: deployment-config.yaml

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Azure CLI
      #   uses: azure/cli@v2
      #   with:
      #     inlineScript: |
      #       echo "Azure CLI setup complete." 

      - name: Checkout mdr_root repository
        uses: actions/checkout@v4  
        with:
          repository: bittib010/mdr_root
          token: ${{ secrets.PAT_TOKEN }}
          path: mdr_root


      # Checkout current repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          path: mdr_cust


      # - name: Install PowerShell Modules
      #   id: install-modules
      #   shell: pwsh
      #   run: |
      #     $InformationPreference = 'Continue'
      #     Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      #     try {
      #       $modulesToInstall = @(
      #         'powershell-yaml'
      #       )
      #       $modulesToInstall | ForEach-Object {
      #         if (-not (Get-Module -Name $_ -ListAvailable)) {
      #           Write-Information -MessageData "Module [$_] not found, installing it..."
      #           Install-Module -Name $_ -ErrorAction Stop
      #         }
      #       }
      #     } catch {
      #       Write-Error -Message "Failed to install module [$_]."
      #       exit 1
      #     }

      # Loop the /mdr_root folders subfolder: artefacts recursively
      - name: List mdr_root artifacts folder
        shell: pwsh
        run: |
          Get-ChildItem /home/runner -recurse | Where-Object {$_.PSIsContainer -and $_.Name -like 'mdr'} | ForEach-Object {
            Write-Host "Found artefacts folder: $($_.FullName)"
          }
