name: Deploy Rules

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master


# env:
#   CONFIG_FILE: deployment-config.yaml

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Azure CLI
      #   uses: azure/cli@v2
      #   with:
      #     inlineScript: |
      #       echo "Azure CLI setup complete." 

      - name: Checkout mdr_root repository
        uses: actions/checkout@v4  
        with:
          repository: bittib010/mdr_root
          token: ${{ secrets.PAT_TOKEN }}
          path: mdr_root


      # Checkout current repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          path: mdr_cust


      # - name: Install PowerShell Modules
      #   id: install-modules
      #   shell: pwsh
      #   run: |
      #     $InformationPreference = 'Continue'
      #     Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      #     try {
      #       $modulesToInstall = @(
      #         'powershell-yaml'
      #       )
      #       $modulesToInstall | ForEach-Object {
      #         if (-not (Get-Module -Name $_ -ListAvailable)) {
      #           Write-Information -MessageData "Module [$_] not found, installing it..."
      #           Install-Module -Name $_ -ErrorAction Stop
      #         }
      #       }
      #     } catch {
      #       Write-Error -Message "Failed to install module [$_]."
      #       exit 1
      #     }

      # Loop the /mdr_root folders subfolder: artefacts recursively
      - name: List mdr_root artifacts folder
        shell: pwsh
        run: |
          # changed: search recursively from the filesystem root "/" with error suppression
          $mdrRootFolders = Get-ChildItem -Path "/" -Directory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq "mdr_root" }
          if ($mdrRootFolders -and $mdrRootFolders.Count -gt 0) {
              foreach ($folder in $mdrRootFolders) {
                  Write-Output "Listing files in: $($folder.FullName)"
                  Get-ChildItem -Path $folder.FullName -Recurse -ErrorAction SilentlyContinue | ForEach-Object { Write-Output $_.FullName }
              }
          } else {
              Write-Output "No mdr_root folder found."
          }
          Write-Output "Current working directory: $(Get-Location)"
          
          # changed: find all YAML files recursively from root "/" with error suppression
          $yamlFiles = Get-ChildItem -Path "/" -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Name -like '*.y*ml' }
          if ($yamlFiles) { 
            Write-Output "Found YAML files:"
            foreach ($file in $yamlFiles) {
              Write-Output $file.FullName
            }
          } else {
            Write-Output "No YAML files found in the repository."
          }
          Get-ChildItem -Path "/home/runner/work/mdr_cust_template/" -Recurse -ErrorAction SilentlyContinue | ForEach-Object { Write-Output $_.FullName }
